import mysql.connector as sql
from tabulate import tabulate
import webbrowser
conn=sql.connect(host = 'localhost',port='3306',user='root',passwd='bwcc')
mycursor=conn.cursor()
mycursor.execute('USE movie_tickets')
print ("LOG IN")
Enter_user=input("Enter userID :")
Enter_passwd=input("Enter password :")
if Enter_user=='asa' and Enter_passwd=='asa':
    print('')
    print('')
    print (" _ _ _ _ _ _ _ _ _ _ _ _WELCOME BACK_ _ _ _ _ _ _ _ _ _ _ _")
    
    if conn.is_connected():
        print('')
        print('')
        print('')
        print ("|$|$$$$$$$$$$ ASA THEATRE BOOKING (AC & NON AC) $$$$$$$$$$|$|")
        print ("|$|                                                       |$|")
        print ("|$|                                                       |$|")
        print ("|$|_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_|$|")
        print ("|$|                                                       |$|")
        print ("|$|~~~~~~~~~~~~~~~~~~~ASA THEATRES~~~~~~~~~~~~~~~~~~~~~~~~|$|")
        print ("|$|                                                       |$|")
        print ("|$|         1.          BOX OFFICE                        |$|")
        print ("|$|         2.    SHOW MOVIE RATING/REVIEW                |$|")
        print ("|$|         3.         BOOKING COUNTER                    |$|")
        print ("|$|         4.      SHOW BOOKING DETAILS                  |$|")
        print ("|$|         5.          CANCELLATION                      |$|")
        print ("|$|         6.          RECIPT BILL                       |$|")
        print ("|$|         7.            EXIT                            |$|")
        print ("|$|_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_|$|")
    ch=int(input("Enter your choice :"))
while True:
    if ch==1:
        mycursor.execute("select * from name")
        data1=mycursor.fetchall()
        print(tabulate(data1,headers=['MOVIES','SHOW_TIME','DATE','PRICE','GENRE'], tablefmt='psql'))
        print ("|~~~~~~~~~~ASA THEATRES~~~~~~~~~~~|")
        print ("|                                 |")
        print ("| 1.         BOX OFFICE           |")
        print ("| 2.  SHOW MOVIE RATING/REVIEW    |")
        print ("| 3.       BOOKING COUNTER        |")
        print ("| 4.     SHOW BOOKING DETAILS     |")
        print ("| 5.        CANCELLATION          |")
        print ("| 6.        RECIPT BILL           |")
        print ("| 7.           EXIT               |")
        print ("|_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_|")
        ch=int(input("Enter your choice :"))
    elif ch==2:
        webbrowser.open('https://www.imdb.com/',new=1)
        print (" ")
        print (" ")
        print ("+~~~~~~~~~~~ASA THEATRES~~~~~~~~~~~+")
        print ("|                                  |")
        print ("| 1.         BOX OFFICE            |")
        print ("| 2.  SHOW MOVIE RATING/REVIEW     |")
        print ("| 3.       BOOKING COUNTER         |")
        print ("| 4.     SHOW BOOKING DETAILS      |")
        print ("| 5.        CANCELLATION           |")
        print ("| 6.        RECIPT BILL            |")
        print ("| 7.           EXIT                |")
        print ("+----------------------------------+")
        ch=int(input("Enter your choice :"))
    elif ch==3:
        mycursor.execute("select S_No, MOVIES, PRICE from name;")
        data1=mycursor.fetchall()
        print(tabulate(data1,headers=['MOVIE CODE','MOVIES','PRICE'], tablefmt='psql'))
        ch=int(input("Select the movie code :"))
        
        if ch==1001:
            MOVIES = ("Alladin")
            print ("Alladin selected")
            PHONE_NO = input("Enter phone number :")
            TICKET = input("Enter total tickets :" )
            SEX = input ("Enter your sex :" )
            FIRST_NAME = input ("Enter your first name :")
            LAST_NAME = input ("Enter your last name :")
            SNACKS = input ("Order your snacks :")
            ins="insert into theater values( '{}','{}','{}','{}','{}','{}','{}')".format(MOVIES,PHONE_NO,TICKET,SEX,FIRST_NAME,LAST_NAME,SNACKS)
            mycursor.execute(ins)
            conn.commit()
            
        elif ch==1002:
            MOVIES = ("Insepion")
            print ("Insepion selected")
            PHONE_NO = input("Enter phone number :")
            TICKET = input("Enter total tickets :" )
            SEX = input ("Enter your sex :" )
            FIRST_NAME = input ("Enter your first name :")
            LAST_NAME = input ("Enter your last name :")
            SNACKS = input ("Order your snacks :")
            ins="insert into theater values( '{}','{}','{}','{}','{}','{}','{}')".format(MOVIES,PHONE_NO,TICKET,SEX,FIRST_NAME,LAST_NAME,SNACKS)
            mycursor.execute(ins)
            conn.commit()

        elif ch==1003:
            MOVIES = ("Kgf2")
            print ("Kgf2 selected")
            PHONE_NO = input("Enter phone number :")
            TICKET = input("Enter total tickets :" )
            SEX = input ("Enter your sex :" )
            FIRST_NAME = input ("Enter your first name :")
            LAST_NAME = input ("Enter your last name :")
            SNACKS = input ("Order your snacks :")
            ins="insert into theater values( '{}','{}','{}','{}','{}','{}','{}')".format(MOVIES,PHONE_NO,TICKET,SEX,FIRST_NAME,LAST_NAME,SNACKS)
            mycursor.execute(ins)
            conn.commit()
    
        elif ch==1004:
            MOVIES = ("War")
            print ("War selected")
            PHONE_NO = input("Enter phone number :")
            TICKET = input("Enter total tickets :" )
            SEX = input ("Enter your sex :" )
            FIRST_NAME = input ("Enter your first name :")
            LAST_NAME = input ("Enter your last name :")
            SNACKS = input ("Order your snacks :")
            ins="insert into theater values( '{}','{}','{}','{}','{}','{}','{}')".format(MOVIES,PHONE_NO,TICKET,SEX,FIRST_NAME,LAST_NAME,SNACKS)
            mycursor.execute(ins)
            conn.commit()
            
        else:
            MOVIES = ("A Walk To Remember")
            print ("A Walk To Remember selected")
            PHONE_NO = input("Enter phone number :")
            TICKET = input("Enter total tickets :" )
            SEX = input ("Enter your sex :" )
            FIRST_NAME = input ("Enter your first name :")
            LAST_NAME = input ("Enter your last name :")
            SNACKS = input ("Order your snacks :")
            ins="insert into theater values( '{}','{}','{}','{}','{}','{}','{}')".format(MOVIES,PHONE_NO,TICKET,SEX,FIRST_NAME,LAST_NAME,SNACKS)
            mycursor.execute(ins)
            conn.commit()
        print (" ticket booked congrats")
        print ("Thank you for visiting asa theatre")
        print ("ratings")
        print (" ")
        print (" ")
        print ("+~~~~~~~~~~~ASA THEATRES~~~~~~~~~~~+")
        print ("|                                  |")
        print ("| 1.         BOX OFFICE            |")
        print ("| 2.  SHOW MOVIE RATING/REVIEW     |")
        print ("| 3.       BOOKING COUNTER         |")
        print ("| 4.     SHOW BOOKING DETAILS      |")
        print ("| 5.        CANCILATION            |")
        print ("| 6.        RECIPT BILL            |")
        print ("| 7.           EXIT                |")
        print ("+----------------------------------+")
        ch=int(input("Enter your choice :"))
    elif ch==4:
        mycursor.execute("select * from theater")
        data=mycursor.fetchall()
        print(tabulate(data,headers=['MOVIES','PHONE_NO','TICKET','SEX','FIRST_NAME','LAST_NAME','SNACKS'], tablefmt='psql'))
        print ("|~~~~~~~~~~ASA THEATRES~~~~~~~~~~~|")
        print ("|                                 |")
        print ("| 1.         BOX OFFICE           |")
        print ("| 2.  SHOW MOVIE RATING/REVIEW    |")
        print ("| 3.       BOOKING COUNTER        |")
        print ("| 4.     SHOW BOOKING DETAILS     |")
        print ("| 5.        CANCILATION           |")
        print ("| 6.        RECIPT BILL           |")
        print ("| 7.           EXIT               |")
        print ("|_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_|")
        ch=int(input("Enter your choice :"))
    elif ch==5:
         mycursor.execute('USE movie_tickets')
         FIR = input("Enter FIRST_NAME :")
         am="DELETE FROM theater WHERE FIRST_NAME='{}'".format(FIR)
         mycursor.execute(am)
         conn.commit()
         mycursor.execute("select * from theater")
         data=mycursor.fetchall()
         print(tabulate(data,headers=['MOVIES','PHONE_NO','TICKET','SEX','FIRST_NAME','LAST_NAME','SNACKS'], tablefmt='psql'))
         print ("TICKET CANCELLATION 'SUCCESSFULLY DONE'")
         print("")
         print ("|~~~~~~~~~~ASA THEATRES~~~~~~~~~~~|")
         print ("|                                 |")
         print ("| 1.         BOX OFFICE           |")
         print ("| 2.  SHOW MOVIE RATING/REVIEW    |")
         print ("| 3.       BOOKING COUNTER        |")
         print ("| 4.     SHOW BOOKING DETAILS     |")
         print ("| 5.        CANCELLATION          |")
         print ("| 6.        RECIPT BILL           |")
         print ("| 7.           EXIT               |")
         print ("|_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_|")
         ch=int(input("Enter your choice :"))
      
    elif ch==6:
        mycursor.execute(" select name.MOVIES,PRICE*TICKET,theater.FIRST_NAME FROM name INNER JOIN theater ON name.MOVIES=theater.MOVIES;")
        data3=mycursor.fetchall()
        print(tabulate(data3,headers=['Payable_amount', 'Name'], tablefmt='psql'))
        print ("|~~~~~~~~~~ASA THEATRES~~~~~~~~~~~|")
        print ("|                                 |")
        print ("| 1.         BOX OFFICE           |")
        print ("| 2.  SHOW MOVIE RATING/REVIEW    |")
        print ("| 3.       BOOKING COUNTER        |")
        print ("| 4.     SHOW BOOKING DETAILS     |")
        print ("| 5.        CANCELLATION          |")
        print ("| 6.        RECIPT BILL           |")
        print ("| 7.           EXIT               |")
        print ("|_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_|")
        ch=int(input("Enter your choice :"))
    else:
        print("EXITED")
        break 
else:
    print('.')
